export const captions = {
  deutsch: "Deutsch",
  infinitiv: "Infinitiv",
  ich: "Ich",
  duM: "Du (Männlich)",
  duW: "Du (Weiblich)",
  er: "Er",
  sie: "Sie",
  wir: "Wir",
  ihr: "Ihr",
  siePlr: "Sie (Plural)",
  audioUpload: "Audio hochladen",
  verbs: "Verben",
  nouns: "Nomen (Inhalt folgt)",
  adjectives: "Adjektive (Inhalt folgt)",
  phrases: "Phrasen (Inhalt folgt)",
  addWord: "+ Neues Wort hinzufügen",
  audioSample: "Audiosample",
  actions: "Aktionen",
};
